name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup wasm-pack
        run: cargo install wasm-pack
      - name: Build with wasm-pack
        run: cd hello-wasm && wasm-pack build --target bundler
      - name: Install dependencies
        run: bun install
      - name: Run tests with cargo
        run: cargo test --manifest-path hello-wasm/Cargo.toml
      - name: Run tests with bun
        run: bun test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup wasm-pack
        run: cargo install wasm-pack
      - name: Build with wasm-pack
        run: cd hello-wasm && wasm-pack build --release --target bundler
      - name: Install dependencies
        run: bun install
      - name: Build with bun
        run: bun run build
      - name: Upload static files as artifact
        uses: actions/upload-artifact@v4
        id: deployment
        with:
          path: dist/
  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
