name: Test

on:
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
  pull_request:
    types: [opened]
    paths:
      - "**/*.rs"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test
