name: Test

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - run: go test
